data-url: "https://huggingface.co/datasets/jason1966/ahsanaseer_top-rated-tmdb-movies-10k/raw/main/top10K-TMDB-movies.csv"
data-df-path: "./data/top10K-TMDB-movies.csv"
embedding-model: "Xenova/all-MiniLM-L6-v2"
embedding-model-dir: "models"


